author:
  email: example@example.com
  name: Chiara Ferrante
baseurl: https://chiaraferrante.netlify.app/
copyright: © Will Faught - License Apache-2.0
languagecode: en-us
enablerobotstxt: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
menu:
  main:
  - identifier: home
    name: Home
    weight: 10
    url: /
  # - identifier: blog
  #   name: Blog
  #   weight: 30
  #   url: /blog/
  - identifier: articles
    name: Publications
    weight: 40
    url: /articles/
  - identifier: projects
    name: Work in progress
    weight: 50
    url: /projects/
  - identifier: cv
    name: CV
    weight: 60
    url: /cv/
#  - identifier: tags
    # name: Tags
    # weight: 70
    # url: /tags/
paginate: 50
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  envelope: chiara.ferrante@ucd.ie
  #discord: http://discord.com/users/example
  #github: https://github.com/example
  #facebook: https://facebook.com/example
  #instagram: https://instagram.com/example
  linkedin: https://www.linkedin.com/in/chiara-ferrante-cf92/
  #reddit: https://reddit.com/u/example
  #twitch: https://www.twitch.tv/example
  twitter: https://twitter.com/ChiaraFerrant
  #youtube: https://www.youtube.com/user/example
  scholar: https://scholar.google.com/citations?hl=en&user=8xHtpJIAAAAJ
theme: "paige"
#timezone: American/LosAngeles
#title: No Borders, No Limits
titlecasestyle: Go
